name: codestyle
on: pull_request

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install pnpm
        run: npm i -g pnpm

      - name: install dependencies
        run: pnpm i

      - name: check codestyle
        run: pnpm lint